create database dmart_analysis;
use dmart_analysis;
SELECT * FROM dmart_analysis.`train (1)`;
RENAME TABLE dmart_analysis  TO dmart_analysis_data;
select count(*)from dmart_analysis_data;
select distinct item_type from dmart_analysis_data;
SELECT * FROM dmart_analysis_data limit 10;
SELECT item_fat_content, AVG(item_mrp) FROM dmart_analysis_data GROUP BY item_fat_content; 
select item_type, avg(item_weight) from dmart_analysis_data where item_weight<10 group by item_type having avg(item_outlet_sales); 
select item_type from dmart_analysis_data where Outlet_Establishment_Year < 1999 ;
SELECT item_type , sum(Item_Outlet_Sales) FROM dmart_analysis_data GROUP BY Item_type;
SELECT * FROM dmart_analysis_data;
SELECT * FROM dmart_analysis_data decs limit 10;
alter table dmart_analysis_data rename column Outlet_Establishment_Year to outlet_year;
alter table dmart_analysis_data rename column item_identifier to item_id;
SELECT item_type,item_outlet_sales,outlet_type, avg(item_outlet_sales)  OVER (PARTITION BY outlet_type ORDER BY outlet_year ) AS year FROM dmart_analysis_data ; 
SELECT * FROM dmart_analysis_data WHERE item_mrp >  ( SELECT AVG(item_mrp) FROM dmart_analysis_data ); 
SELECT item_id, item_type, outlet_year, DATEDIFF('1999', outlet_year) AS years_until_2006 FROM dmart_analysis_data aesc limit 10; 
select COUNT(*) AS sales_count from dmart_analysis_data where item_outlet_sales > 1000;
select count(*)from dmart_analysis_data where item_fat_content = 'low fat'; 
SELECT item_type, item_mrp, CASE WHEN item_mrp > 100 THEN 'High' WHEN item_mrp BETWEEN 50 AND 80 THEN 'Medium' ELSE 'Low' END AS mrp_category FROM dmart_analysis_data;
create user shiva identified by "12345";
grant select on dmart_analysis_data to shiva;
revoke select on dmart_analysis_data from shiva;
savepoint sp1;